const colors = require("tailwindcss/colors");

module.exports = {
  content: ["index.html", "./src/**/*.{js,jsx,ts,tsx,vue,html}"],
  theme: {
    extend: {
      textColor: {
        violet: colors.violet,
        sky: colors.sky,
        blue: colors.blue,
        indigo: colors.indigo,
        purple: colors.purple,
      },
    },
  },
  safelist: [
    'bg-gradient-to-br',
    'from-cyan-400', 
    'to-indigo-700', 
    'bg-clip-text', 
    'text-transparent',
    'leading-none',
    'max-w-[16rem]',
    'lg:max-w-full',
    'text-xs',
    'text-sm',
    'text-normal',
    'text-lg',
    'text-xl',
    'text-2xl',
    'text-3xl',
    'text-4xl',
    'text-5xl',
    'text-6xl',
    'text-7xl',
    'text-8xl',
    'text-9xl',
    'sm:text-xl',
    'sm:text-2xl',
    'sm:text-3xl',
    'sm:text-4xl',
    'sm:text-5xl',
    'sm:text-6xl',
    'sm:text-7xl',
    'sm:text-8xl',
    'sm:text-9xl',
    'md:text-xl',
    'md:text-2xl',
    'md:text-3xl',
    'md:text-4xl',
    'md:text-5xl',
    'md:text-6xl',
    'md:text-7xl',
    'md:text-8xl',
    'md:text-9xl',
    'lg:text-xl',
    'lg:text-2xl',
    'lg:text-3xl',
    'lg:text-4xl',
    'lg:text-5xl',
    'lg:text-6xl',
    'lg:text-7xl',
    'lg:text-8xl',
    'lg:text-9xl',
    'xl:text-xl',
    'xl:text-2xl',
    'xl:text-3xl',
    'xl:text-4xl',
    'xl:text-5xl',
    'xl:text-6xl',
    'xl:text-7xl',
    'xl:text-8xl',
    'xl:text-9xl',
  ],
  plugins: [require("daisyui")],
};
